#+TITLE: vis-workflow-timeline
#+AUTHOR: Petros Papapanagiotou

[[https://img.shields.io/badge/version-0.0.2-brightgreen.svg]]
[[https://opensource.org/licenses/Apache-2.0][https://img.shields.io/badge/license-Apache%202.0-yellowgreen.svg]]

An application of [[https://github.com/visjs/vis-timeline][vis-timeline]] to workflow data, particularly those generated by [[http://docs.workflowfm.com/pew/][PEW]] and [[http://docs.workflowfm.com/proter/][Proter]].

| [[https://aiml.inf.ed.ac.uk/][Artificial Intelligence Modelling Lab]] |
| [[https://web.inf.ed.ac.uk/aiai][Artificial Intelligence and its Applications Institute]] |
| [[https://www.ed.ac.uk/informatics/][School of Informatics, University of Edinburgh]] |


* Usage

The library is bundled in the file: [[https://github.com/workflowfm/vis-workflow-timeline/releases/download/v0.0.1/bundle.js][bundle.js]]

There are currently 2 versions provided:
1. ~workflowUnitTimeline~ uses plain numbers as units of duration.
2. ~workflowTimeline~ uses Dates and millisecond intervals as units of duration.

Example usage in the browser can be found in [[https://github.com/workflowfm/vis-workflow-timeline/tree/main/examples][this directory]].

Data samples are also provided, generated by the [[https://github.com/workflowfm/HealthcareHandover][Healthcare Handover]] example.


* Build

At the moment, vis-workflow-timeline is designed to be bundled for the browser using ~npm~ and ~browserify~.

Install ~browserify~:
#+BEGIN_SRC sh
npm install -g browserify
#+END_SRC

Build the bundle:
#+BEGIN_SRC sh
npm run build
#+END_SRC 

This will create the file ~examples/bundle.js~ which you can load up through [[https://github.com/workflowfm/vis-workflow-timeline/blob/main/examples/local.html][examples/local.html]]

* Authors
:PROPERTIES:
:CUSTOM_ID: authors
:END:

** Maintainer

   [[https://github.com/PetrosPapapa][Petros Papapanagiotou]] - petros@workflowfm.com - [[https://twitter.com/petrospapapa][@PetrosPapapa]]

** Contributors

   A big thank you to the following contributors in order of appearance:

   - [[https://github.com/JMaio][Joao Maio]]
   - [[https://github.com/abhishekpandey07][Abhishek Pandey]]
   - [[https://github.com/pilif0][Filip Smola]]

* License

Distributed under the Apache 2.0 license. See [[./LICENSE][LICENSE]] for more information.

Copyright \copy 2019-2021 [[https://www.ed.ac.uk/][The University of Edinburgh]] and [[#authors][contributors]]
